version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app --reload
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  fastapi:
    build: ./services/fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/fastapi/:/usr/src/app/
    ports:
      - 8001:8000

  room:
    build: ./services/room_reservation
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/room_reservation/:/usr/src/app/
    ports:
      - 8002:8000
  parser:
      build: ./services/parser
      command: celery -A tasks worker --loglevel=INFO
      env_file:
        - ./.env.dev
      depends_on:
        - db
        - redis
  redis:
    image: redis:6.0.10-alpine

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data: